name: AnvilWallet
options:
  bundleIdPrefix: com.anvilwallet
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

configFiles:
  Debug: Secrets.xcconfig
  Release: Secrets.xcconfig

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"

packages:
  reown-swift:
    url: https://github.com/reown-com/reown-swift
    from: "1.0.0"

targets:
  AnvilWallet:
    type: application
    platform: iOS
    sources:
      - path: AnvilWallet
        excludes:
          - "**/.DS_Store"
    resources:
      - path: AnvilWallet/Resources/Assets.xcassets
    dependencies:
      - framework: WalletCoreFramework.xcframework
        embed: false
      - package: reown-swift
        product: ReownWalletKit
      - target: AnvilWalletWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anvilwallet.app
        PRODUCT_NAME: AnvilWallet
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_EtherscanApiKey: "$(ETHERSCAN_API_KEY)"
        INFOPLIST_KEY_ReownProjectID: "$(REOWN_PROJECT_ID)"
        INFOPLIST_KEY_SocketApiKey: "$(SOCKET_API_KEY)"
        INFOPLIST_KEY_ZeroExApiKey: "$(ZERO_EX_API_KEY)"
        INFOPLIST_KEY_MoonPayApiKey: "$(MOONPAY_API_KEY)"
        INFOPLIST_KEY_TransakApiKey: "$(TRANSAK_API_KEY)"
        INFOPLIST_KEY_SupportURL: "$(SUPPORT_URL)"
        INFOPLIST_KEY_PrivacyPolicyURL: "$(PRIVACY_POLICY_URL)"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSCameraUsageDescription: "Anvil uses the camera to scan QR codes"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "Anvil uses Face ID to protect your wallet"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Save QR code images to your photo library"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"
        INFOPLIST_KEY_CFBundleDisplayName: "Anvil"
        ITSAppUsesNonExemptEncryption: true
        ITSEncryptionExportComplianceCode: ""
        SWIFT_INCLUDE_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/AnvilWallet/Generated"
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/AnvilWallet/Generated"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
        OTHER_LDFLAGS:
          - "$(inherited)"

  AnvilWalletWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: AnvilWalletWidget
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anvilwallet.app.widget
        PRODUCT_NAME: AnvilWalletWidget
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "Anvil Portfolio"
        INFOPLIST_KEY_NSExtension_NSExtensionPointIdentifier: "com.apple.widgetkit-extension"
        SWIFT_VERSION: "5.9"
