name: AnvilWallet
options:
  bundleIdPrefix: com.anvilwallet
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: false
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"

packages:
  reown-swift:
    url: https://github.com/reown-com/reown-swift
    from: "1.0.0"

targets:
  AnvilWallet:
    type: application
    platform: iOS
    sources:
      - path: AnvilWallet
        excludes:
          - "**/.DS_Store"
    resources:
      - path: AnvilWallet/Resources/Assets.xcassets
    dependencies:
      - framework: WalletCoreFramework.xcframework
        embed: true
      - package: reown-swift
        product: ReownWalletKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.anvilwallet.app
        PRODUCT_NAME: AnvilWallet
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSCameraUsageDescription: "AnvilWallet needs camera access to scan QR codes"
        INFOPLIST_KEY_NSFaceIDUsageDescription: "AnvilWallet uses Face ID to authenticate transactions"
        INFOPLIST_KEY_CFBundleDisplayName: "Anvil"
        SWIFT_INCLUDE_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/AnvilWallet/Generated"
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/AnvilWallet/Generated"
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
        OTHER_LDFLAGS:
          - "$(inherited)"
