#!/bin/bash
# inject-binary-hash.sh — Xcode Build Phase script that computes the SHA-256
# hash of the compiled executable and writes it to a generated Swift file.
#
# Usage: Add as a "Run Script" build phase in Xcode AFTER the "Compile Sources"
#        and "Link Binary" phases, for Release builds only.
#
# The generated file is imported by AppIntegrityChecker to verify binary integrity.

set -euo pipefail

GENERATED_DIR="${SRCROOT}/AnvilWallet/Generated"
OUTPUT_FILE="${GENERATED_DIR}/BinaryHash.swift"
EXECUTABLE="${BUILT_PRODUCTS_DIR}/${EXECUTABLE_PATH}"

# Only inject for Release builds
if [ "${CONFIGURATION}" != "Release" ]; then
    echo "Skipping binary hash injection for ${CONFIGURATION} build"
    # Write empty hash for non-release
    mkdir -p "$GENERATED_DIR"
    cat > "$OUTPUT_FILE" << 'SWIFT'
// Auto-generated — do not edit manually.
// Binary hash injection is only active for Release builds.
enum GeneratedBinaryHash {
    static let executableHash = ""
}
SWIFT
    exit 0
fi

if [ ! -f "$EXECUTABLE" ]; then
    echo "error: Executable not found at $EXECUTABLE"
    exit 1
fi

HASH=$(shasum -a 256 "$EXECUTABLE" | awk '{print $1}')

mkdir -p "$GENERATED_DIR"
cat > "$OUTPUT_FILE" << SWIFT
// Auto-generated by inject-binary-hash.sh — do not edit manually.
// Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
enum GeneratedBinaryHash {
    static let executableHash = "$HASH"
}
SWIFT

echo "Injected binary hash: $HASH"
